### ISSUE TITLE
Vacancy: envia number, não aceita number

### ISSUE THREAD

**Issue by annecchini** [SEAD-UFES/publications#18]
O problema:
01 -Faça um GET de uma vacancy. (Observe qtd)
02 - Tente fazer um POST da vacancy com qtd no mesmo formato.
03 - Observe o erro.
04 - O erro ocorre porque, isNumeric espera um string e recebe um numero.
05 - Acredito ser falha na consistência entregar um numero e não aceitar um numero.

A solução:
01 - Ou forçar o numero como string em no GET (specific e list) - Não acho muito legal.
02 - Ou fazer a validação aceitar string e number. - Acredito que seja legal isso.

**Comment by edo9k** [comment]
Tá no pull request -> #20

**Comment by annecchini** [comment]
Ok, Fechando a issue.
