### ISSUE TITLE
Validator.isNumeric lança erro com números

### ISSUE THREAD

**Issue by edo9k** [SEAD-UFES/publications#23]
Dois problemas com o Validator.isNumeric:

- lança erro quando o parâmetro é um número (TypeError)
- não bloqueia float, ex: "1.1"

Ideia: substituir ele por uma função que faça a checagem, usando Number para converter e Number.isInteger para checar se o valor é válido.

**Comment by annecchini** [comment]
Ainda não fiz os teste de forma mais extensiva, mas...

Se for numero força que ele seja string.
Pega a string e verifica se ela representa um numero inteiro.

```
const { isInt } = require('validator')
//value have to be a number
  if (typeof value === 'number') value = value.toString()
  if (!isInt(value)) {
    return 'Este campo deve ser um número inteiro.'
  }
```

**Comment by annecchini** [comment]
Não lembro mais...
