### ISSUE TITLE
definir idioma dos commits

### ISSUE THREAD

**Issue by edo9k** [SEAD-UFES/publications#4]
Eu tava _comitando_ em inglês nem sei dizer o porquê. Continuar? _Comitar_ em português? (acho que faz mas sentido, mas sei lá, definam ae) @wagnerperin @israelhenrique @annecchini @natodp

**Comment by natodp** [comment]
Seus registros parecem estar em português, os do Wagner que estão em inglês. Se todos estiverem familiarizados com o inglês, acredito que possa ser nesse idioma, para não gerar um _portuglês_ em virtude dos termos utilizados no código.
